-- ===================================================
-- Supabase Schema for Meal Tracker
-- ===================================================

-- 1. 创建 meals 数据表 (包含 Week 2 PFC 字段)
create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  food_name text not null,
  calories integer not null check (calories >= 0),
  protein numeric default 0 check (protein >= 0),
  fat numeric default 0 check (fat >= 0),
  carbs numeric default 0 check (carbs >= 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 若已存在 Week 1 版本的 meals 表，可运行以下脚本补充 PFC 字段：
alter table public.meals 
  add column if not exists protein numeric default 0,
  add column if not exists fat numeric default 0,
  add column if not exists carbs numeric default 0;

-- 2. 开启行级安全策略 (Row Level Security, RLS)
alter table public.meals enable row level security;

-- 3. 添加匿名读取策略（允许前端 anon 角色读取列表）
create policy "Allow anonymous select on meals"
  on public.meals
  for select
  to anon, authenticated
  using (true);

-- 4. 添加匿名插入策略（允许前端 anon 角色插入食物数据）
create policy "Allow anonymous insert on meals"
  on public.meals
  for insert
  to anon, authenticated
  with check (true);

-- 5. （可选）添加匿名删除策略（便于调试和清理测试数据）
create policy "Allow anonymous delete on meals"
  on public.meals
  for delete
  to anon, authenticated
  using (true);

-- 6. 添加索引以优化按时间倒序查询的性能
create index if not exists idx_meals_created_at on public.meals (created_at desc);
